version: '3'
services:
  nginx:
    image: nginx:1.23-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/data/nginx:/etc/nginx/conf.d
  
  certbot:
    image: certbot/certbot
    
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - /home/data/certbot/conf:/etc/letsencrypt 
      - /home/data/certbot/www:/var/www/certbot
      